repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.19  # set by `pre-commit autoupdate`
    hooks:
      - id: ruff-check
        args: [--fix]
      - id: ruff-format
  - repo: https://github.com/astral-sh/ty-pre-commit
    rev: v0.0.53  # set by `pre-commit autoupdate`
    hooks:
      - id: ty
